### ISSUE TITLE
The Haste lang link in the readme points to a bogus website

### ISSUE THREAD

**Issue by alllex** [sharkdp/yinsh#11]
The http://haste-lang.org/ link from the readme points to a website that seems to have been bought by some fraudulent actors.

**Comment by sharkdp** [comment]
Thank you, I replaced it with a link to a GitHub repository.

It's unfortunate that Haste is not really developed anymore. Last time I tried, I couldn't even compile the frontend anymore. If I find the time, I need to rewrite this project in another language (or at least the frontend). ==> #8
