### ISSUE TITLE
Version of Haste Compiler 

### ISSUE THREAD

**Issue by SaiKeshav** [sharkdp/yinsh#5]
What is the version of hastec and ghc, that is required to compile this code? I am facing issues while trying to perform `make` with the latest version of the compilers. I suspect it could be because I am using the wrong version.

**Comment by sharkdp** [comment]
Thank you for your feedback.

I'm afraid I don't know :flushed:. I haven't worked on this project for a while. I guess we could figure out the supported GHC/Haste versions by looking at the commit-timestamps for the last relevant changes.

I'd also be happy to accept PRs which would update the code to the latest compiler versions (hoping that this wouldn't be too hard to fix).

**Comment by sharkdp** [comment]
closing in favor of #8
